---
connectionconf:
  access_key: AWS_ACCESS_KEY_ID
  secret_key: AWS_SECRET_ACCESS_KEY
  region: eu-north-1
  bucket: dewp-test-bucket
  folder: output
  database: covid-19
  query:
    nytimes_data_in_usa_us_contries: SELECT * FROM "covid-19"."nytimes_data_in_usa_us_countryus_county" limit 1000
    rearc_covid19_testing_data_states_daily: select * from
      "covid-19"."rearc_covid19_testing_data_states_dailystates_daily" limit 1000
    rearc_usa_hostipal_beds: select * from "covid-19"."rearc_usa_hostipal_bedsrearc_usa_hospital_beds" limit 1000
    enigma_jhud: select * from "covid-19"."enigma_jhud" limit 1000
etlconf:
  fact_covid_1_columns:
    - fips
    - province_state
    - country_region
    - confirmed
    - deaths
    - recovered
    - active
  fact_covid_2_columns:
    - fips
    - positive
    - negative
    - hospitalizedcurrently
    - hospitalized
    - hospitalizeddischarged
  dim_region_1_columns:
    - fips
    - province_state
    - country_region
    - latitude
    - longitude
  dim_region_2_columns:
    - fips
    - county
    - state
  dim_hospital:
    - fips
    - state_name
    - latitude
    - longtitude
    - hq_address
    - hospital_type
    - hospital_name
    - hq_city
    - hq_state
  dim_date:
    - fips
    - date
logging:
  version: 1
  formatters:
    dewp:
      format: dewp Transformer - %(asctime)s - %(levelname)s - %(message)s
  handlers:
    console:
      class: logging.StreamHandler
      formatter: dewp
      level: DEBUG
  root:
    level: DEBUG
    handlers:
      - console
